[package]
name = "cgmapper"
version = "0.1.0"
authors = ["Maximilian Huber <52167836+maxivhuber@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
serde_json = "1.0"
